# Generated by Django 3.2.25 on 2024-12-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_policies', '0005_alter_passwordrecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='passwordrecord',
            name='password',
            field=models.CharField(db_index=True, editable=False, max_length=128, verbose_name='Password hash'),
        ),
    ]
